apiVersion: v1
kind: Secret
metadata:
  name: fireworks-secret
type: Opaque
stringData:
  DB_PASSWORD: "Test12345"
  DATABASE_URL: "mysql://root:Test12345@mysql:3306/fireworks_db"
  SESSION_SECRET: "fireworks-secret-key-2026"
